workflows:
  flutter-ios-testflight:
    name: Flutter iOS TestFlight
    environment:
      flutter: 3.32.8
      xcode: 16.2
      groups:
        - firebase-ios

    scripts:
      - name: Load Firebase configuration
        script: |
          echo "$IOS_FIREBASE_SECRET" > ios/Runner/GoogleService-Info.plist
          echo "GoogleService-Info.plist project ID:"
          plutil -p ios/Runner/GoogleService-Info.plist | grep PROJECT_ID
          echo "Bundle ID do app (Info.plist):"
          /usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" ios/Runner/Info.plist
          mkdir -p ios/certs
          # Criar P12
          echo "$IOS_CERTIFICATE" | base64 --decode > ios/certs/certificate.p12
          # Criar Provisioning Profile
          echo "$IOS_PROVISIONING_PROFILE" | base64 --decode > ios/certs/profile.mobileprovision
          security create-keychain -p "" build.keychain
          security import ios/certs/certificate.p12 -k ~/Library/Keychains/build.keychain -P "$IOS_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          echo "Certificados disponíveis no keychain:"
          security find-identity -v -p codesigning ~/Library/Keychains/build.keychain
          # Verificar provisioning profiles
          echo "Provisioning profiles instalados:"
          ls ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Build iOS Release IPA
        script: flutter build ipa --release --export-options-plist ios/ExportOptions.plist

      - name: Verify Bundle ID in built IPA
        script: |
          IPA_PATH="build/ios/ipa/Runner.ipa"
          unzip -q $IPA_PATH -d tmp_ipa
          echo "Bundle ID dentro do .ipa:"
          /usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" tmp_ipa/Payload/Runner.app/Info.plist

    artifacts:
      - build/ios/ipa/Runner.ipa
