workflows:
  flutter-ios-simulator:
    name: Flutter iOS Simulator
    environment:
      flutter: 3.32.8
      xcode: 16.2
      groups:
        - firebase-ios
    scripts:
      - name: Load Firebase configuration
        script: |
          #!/usr/bin/env sh
          set -e
          echo $IOS_FIREBASE_SECRET > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist

          echo "Usando GoogleService-Info.plist:"
          cat ios/Runner/GoogleService-Info.plist | grep PROJECT_ID || true
          plutil -p ios/Runner/GoogleService-Info.plist | grep PROJECT_ID
          echo "Usando Bundle ID:"
          plutil -p ios/Runner/Info.plist | grep BUNDLE_ID
          /usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" "ios/Runner/Info.plist"


      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Build iOS Release IPA
        script: |
          flutter build ios --release \
            --no-codesign=false \
            --flavor production \
            # opcional: definir o team
            # --build-name=1.0.0 \
            # --build-number=1

      - name: Verify Bundle ID in built IPA
        script: |
          IPA_PATH="build/ios/ipa/Runner.ipa"
          unzip -q $IPA_PATH -d tmp_ipa
          /usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" tmp_ipa/Payload/Runner.app/Info.plist

    artifacts:
      - build/ios/ipa/Runner.ipa