workflows:
  flutter-ios-testflight:
    name: Flutter iOS TestFlight
    environment:
      flutter: 3.32.8
      xcode: 16.2
      groups:
        - firebase-ios

    scripts:
      - name: Load Firebase configuration
        script: |
          echo "$IOS_FIREBASE_SECRET" > ios/Runner/GoogleService-Info.plist
          echo "GoogleService-Info.plist project ID:"
          plutil -p ios/Runner/GoogleService-Info.plist | grep PROJECT_ID
          echo "Bundle ID do app (Info.plist):"
          /usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" ios/Runner/Info.plist

      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Build iOS Release IPA
        script: flutter build ipa --release --export-options-plist ios/ExportOptions.plist

      - name: Verify Bundle ID in built IPA
        script: |
          IPA_PATH="build/ios/ipa/Runner.ipa"
          unzip -q $IPA_PATH -d tmp_ipa
          echo "Bundle ID dentro do .ipa:"
          /usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" tmp_ipa/Payload/Runner.app/Info.plist

    artifacts:
      - build/ios/ipa/Runner.ipa
