// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMpOadW9XveK3u9_L1SGqsueJRG1uB8Jc',
    appId: '1:962139125344:web:XXXXXXXXX',
    messagingSenderId: '962139125344',
    projectId: 'firstdoctor-br',
    authDomain: 'firstdoctor-br.firebaseapp.com',
    storageBucket: 'firstdoctor-br.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMpOadW9XveK3u9_L1SGqsueJRG1uB8Jc',
    appId: '1:962139125344:android:c92ff06f898eb5d44cf505',
    messagingSenderId: '962139125344',
    projectId: 'firstdoctor-br',
    storageBucket: 'firstdoctor-br.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-x4fCr7fNMN9FCBBoQxhNHn4nF2LCLRQ',
    appId: '1:962139125344:ios:d8ce232ba61346934cf505',
    messagingSenderId: '962139125344',
    projectId: 'firstdoctor-br',
    storageBucket: 'firstdoctor-br.firebasestorage.app',
    iosBundleId: 'com.octocm.firstdoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-x4fCr7fNMN9FCBBoQxhNHn4nF2LCLRQ',
    appId: '1:962139125344:ios:d8ce232ba61346934cf505',
    messagingSenderId: '962139125344',
    projectId: 'firstdoctor-br',
    storageBucket: 'firstdoctor-br.firebasestorage.app',
    iosBundleId: 'com.octocm.firstdoctor',
  );

}