name: Build iOS and Upload to TestFlight

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    env:
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      ASC_API_KEY_ID: ${{ secrets.ASC_API_KEY_ID }}
      ASC_API_KEY_P8: ${{ secrets.ASC_API_KEY_P8 }}
      ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
      BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
      IOS_CERTIFICATE: ${{ secrets.IOS_CERTIFICATE }}                   # base64 de UMA LINHA do .p12
      IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }} # ex: vPNZskLS
      IOS_PROVISIONING_PROFILE: ${{ secrets.IOS_PROVISIONING_PROFILE }} # base64 do .mobileprovision
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

    steps:
      # 1) Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Flutter para iOS
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'
          architecture: 'arm64'

      - name: Install dependencies
        run: flutter pub get

      # 3) Preparar diretórios e decodificar credenciais
      - name: Prepare & decode credentials
        run: |
          mkdir -p ios/certs
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mkdir -p ~/private_keys

          # Decode usando BSD base64 do macOS (-D)
          printf "%s" "$IOS_CERTIFICATE" | base64 -D > ios/certs/certificate.p12
          printf "%s" "$IOS_PROVISIONING_PROFILE" | base64 -D > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
          printf "%s" "$ASC_API_KEY_P8" | base64 -D > ~/private_keys/AuthKey_${ASC_API_KEY_ID}.p8
          chmod 600 ~/private_keys/AuthKey_${ASC_API_KEY_ID}.p8

          echo "P12 size/type:"
          ls -l ios/certs/certificate.p12
          file ios/certs/certificate.p12

  # 4) Validar P12 com openssl e extrair PEMs (chave + cert) e converter chave p/ PKCS#8
      - name: Validate & extract from PKCS12
        run: |
          # Valida senha do P12 (se falhar, sai)
          /usr/bin/openssl pkcs12 -in ios/certs/certificate.p12 -nokeys -passin pass:"$IOS_CERTIFICATE_PASSWORD" >/dev/null
          echo "P12 password OK (openssl)"

          # Extrai chave privada (PEM) e certificado (PEM)
          /usr/bin/openssl pkcs12 -in ios/certs/certificate.p12 -nocerts -nodes -passin pass:"$IOS_CERTIFICATE_PASSWORD" -out ios/certs/key.pem
          /usr/bin/openssl pkcs12 -in ios/certs/certificate.p12 -clcerts -nokeys -passin pass:"$IOS_CERTIFICATE_PASSWORD" -out ios/certs/cert.pem

          # Converte a chave para PKCS#8 sem criptografia (o security adora isso)
          /usr/bin/openssl pkcs8 -topk8 -nocrypt -in ios/certs/key.pem -out ios/certs/key_pkcs8.pem

          chmod 600 ios/certs/key.pem ios/certs/key_pkcs8.pem ios/certs/cert.pem
          echo "PEMs prontos:"
          ls -l ios/certs/key.pem ios/certs/key_pkcs8.pem ios/certs/cert.pem

      # 5) Keychain e import (importa a chave PKCS#8 e o certificado)
      - name: Setup keychain and import key/cert
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain

          # Importa a CHAVE PRIVADA em PKCS#8
          security import ios/certs/key_pkcs8.pem \
            -k build.keychain \
            -t priv \
            -f pkcs8 \
            -A \
            -T /usr/bin/codesign \
            -T /usr/bin/security

          # Importa o CERTIFICADO (PEM). Deixa auto-detectar ou usa pemseq.
          security import ios/certs/cert.pem \
            -k build.keychain \
            -t cert \
            -f pemseq \
            -A \
            -T /usr/bin/codesign \
            -T /usr/bin/security

          # Garante acesso da chave para as tools da Apple
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" build.keychain

          # Conferência (não falha o job)
          security find-identity -v -p codesigning build.keychain || true



      # 6) Build IPA
      - name: Build IPA
        run: |
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist

      # 7) Fastlane
      - name: Install fastlane
        run: sudo gem install fastlane -NV

      # 8) Upload para TestFlight
      - name: Upload to TestFlight via fastlane
        run: |
          IPA_PATH="$(ls build/ios/ipa/*.ipa | head -n 1)"
          echo "Uploading: $IPA_PATH"
          fastlane pilot upload \
            --ipa "$IPA_PATH" \
            --api_key_path ~/private_keys/AuthKey_${ASC_API_KEY_ID}.p8
